language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
env:
  - process.env.CI = false
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $github_token
#  local_dir: build
#  on:
#    branch: master